---

- name: Create prometheus directory
  file:
    path: /home/{{ ansible_user }}/home-assistant/prometheus
    state: directory

- name: Create prometheus data directory
  file:
    path: /home/{{ ansible_user }}/home-assistant/prometheus_data
    state: directory

- name: Launch prometheus container
  become: true
  docker_container:
    name: prometheus
    restart_policy: always
    image: prom/prometheus:latest
    user: "1000"
    volumes:
      - /home/{{ ansible_user }}/home-assistant/prometheus_data:/prometheus
      - /home/{{ ansible_user }}/home-assistant/prometheus:/etc/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
    - "9090:9090"
    env:
      TZ: Europe/Amsterdam
