---

- name: Create grafana directory
  file:
    path: /home/{{ ansible_user }}/home-assistant/grafana
    state: directory

- name: "Launch grafana container"
  become: true
  docker_container:
    name: grafana
    user: "0"
    restart_policy: unless-stopped
    image: grafana/grafana:latest
    volumes:
    - /home/{{ ansible_user }}/home-assistant/grafana:/var/lib/grafana
    ports:
    - "3000:3000"
    privileged: true
    env:
      TZ: Europe/Amsterdam
