---
# file: site.yml
- hosts: minh-ubuntu-homeassistant
  roles:
    - homeassistant
    - homebridge
    - portainer
    - nginx_proxy_manager
    - esxi_vm

- hosts: minh-ubuntu-api
  roles:
    - portainer_agent
    - pihole
    - wireguard
    - esxi_vm

- hosts: minh-ubuntu-ansible
  roles:
    - portainer_agent
    - git
    - docker
    - esxi_vm
    - ansible_semaphore
