---

- name: Launch portainer_agent container
  become: true
  community.docker.docker_container:
    name: portainer_agent
    restart_policy: always
    image: portainer/agent:latest
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9001:9001"
