---

- name: Create homebridge directory
  file:
    path: /home/{{ ansible_user }}/homebridge
    state: directory

- name: Launch homebridge container
  become: true
  docker_container:
    name: homebridge
    restart_policy: always
    image: oznu/homebridge:latest
    volumes:
      - /home/{{ ansible_user }}/homebridge:/homebridge
    network_mode: host
    env:
      TZ: Europe/Amsterdam
