---

- name: Create semaphore directory
  file:
    path: /home/{{ ansible_user }}/semaphore
    state: directory

- name: Launch semaphore container
  become: true
  docker_container:
    name: semaphore
    user: "0"
    restart_policy: unless-stopped
    image: semaphoreui/semaphore:latest
    volumes:
      - /home/{{ ansible_user }}/semaphore/home:/etc/semaphore
      - /home/{{ ansible_user }}/semaphore/lib:/var/lib/semaphore
    ports:
      - "3000:3000"
    privileged: true
    env:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: "{{ semaphore_password }}"
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
