---

- name: Create portainer data directory
  become: true
  file:
    path: /home/{{ ansible_user }}/{{ data_folder }}/portainer_data
    state: directory

- name: "Launch portainer container"
  become: true
  docker_container:
    name: portainer-ce
    restart_policy: always
    image: portainer/portainer-ce:latest
    volumes:
    - /home/{{ ansible_user }}/{{ data_folder }}/portainer_data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "9000:9000"

- name: Create PiHole etc directory
  become: true
  file:
    path: /home/{{ ansible_user }}/{{ data_folder }}/pihole/etc
    state: directory

- name: Create PiHole dnsmasq directory
  become: true
  file:
    path: /home/{{ ansible_user }}/{{ data_folder }}/pihole/dnsmasq.d
    state: directory

- name: Allow access to tcp port 53
  become: true
  community.general.ufw:
    rule: allow
    port: '53'
    proto: tcp

- name: Allow access to udp port 53
  become: true
  community.general.ufw:
    rule: allow
    port: '53'
    proto: udp

- name: Allow access to tcp port 443
  become: true
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Allow access to tcp port 5335
  become: true
  community.general.ufw:
    rule: allow
    port: '5335'
    proto: tcp

- name: Enable UFW
  become: true
  community.general.ufw:
    state: enabled   

- name: "Launch PiHole container"
  become: true
  docker_container:
    name: pihole
    restart_policy: unless-stopped
    image: pihole/pihole:latest
    volumes:
    - /home/{{ ansible_user }}/{{ data_folder }}/pihole/etc:/etc/pihole
    - /home/{{ ansible_user }}/{{ data_folder }}/pihole/dnsmasq.d:/etc/dnsmasq.d
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "80:80/tcp"
    env:
      TZ: 'europe/amsterdam'
      WEBPASSWORD: "{{ pihole_password }}"
      FTLCONF_LOCAL_IPV4: 192.168.50.152
      FTLCONF_REPLY_ADDR4: 192.168.50.152

